gems:
  - bourbon
  - neat
  - jekyll-sitemap
  - jekyll-archives

# Structure configuration
source: source
destination: build

assets:
  dirname: assets
  baseurl: /assets/
  cachebust: soft
  source:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  debug: true

jekyll-archives:
  enabled: all
  layouts:
    year: archive
    month: archive
    day: archive
    tag: archive-taxonomy
    category: archive-taxonomy
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'

# Site settings
title: "Myles' Lab"
description: Myles Braithwaite's Programming Laboratory.
permalink: /:year/:month/:day/:title/

# Author information
author: Myles Braithwaite
email: me@mylesbraithwaite.org

# URL settings
url: "http://127.0.0.1:4000"
baseurl: ""
cdn_url: ""
cdn_baseurl: "uploads"
weblab_url: "http://127.0.0.1:8000"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: []
