gems:
  - jekyll-sitemap
  - jekyll-archives

# Structure configuration
source: source
destination: build

assets:
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  debug: true

jekyll-archives:
  enabled: all
  layouts:
    year: archive
    month: archive
    day: archive
    tag: archive-taxonomy
    category: archive-taxonomy
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'

jekyll_pages_api_search:
  index_fields:
    title:
      boost: 10
    subtitle:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
      boost: 1

# Site settings
title: "Myles' Lab"
description: Myles Braithwaite's Programming Laboratory.
permalink: /:year/:month/:day/:title/

# Author information
author: Myles Braithwaite
email: me@mylesbraithwaite.org

# URL settings
url: "http://127.0.0.1:4000"
baseurl: ""
cdn_url: ""
cdn_baseurl: "uploads"
weblab_url: "http://127.0.0.1:8000"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: []

# CodePen settings
codepen_username: mylesb
